# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kollegianer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for kollegianer
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

  # target 'kollegianer-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
  # end

  # target 'kollegianerTests' do
    # inherit! :search_paths
    # Pods for testing
  # end

end
